### ISSUE TITLE
make creates an error

### ISSUE THREAD

**Issue by vinayakumarr** [davidmcgrew/joy#3]
I had downloaded and when i try to execute make command generates the following error. Please check
![error](https://cloud.githubusercontent.com/assets/18217467/18393515/490561d2-76d3-11e6-8619-2bce202d000d.png)

**Comment by davidmcgrew** [comment]
There are missing dependancies.   The README file should have documented these better; sorry for the bother.   I believe that the right incantation to get pcap2flow working on debian linux is: 
`sudo apt-get install libssl zlib`.

To get all of the components working, including saltUI, requires these other packages as well: 
`sudo apt-get install python-dev python-numpy python-setuptools python-scipy libatlas-dev libatlas3gf-base whois`

Please let me know if there are any other issues in compiling.

**Comment by vinayakumarr** [comment]
I have installed sudo apt-get install libssl0.9.8 libssl-dev and cd zlib-1.2.8, ./configure --prefix=/usr/local/zlib, make, sudo make install.

After installing these two successfully i tried to execute command. This also gives same error as i mentioned above

**Comment by vinayakumarr** [comment]
Generates the following error
![error](https://cloud.githubusercontent.com/assets/18217467/18429327/5b24499a-78f0-11e6-9457-27e8d6b58222.png)
. Please have a look

**Comment by davidmcgrew** [comment]
Oops, I had failed to add example.c in last night's commit.  I just now pushed the file into the repository, sorry for the bother.

**Comment by vinayakumarr** [comment]
thanks for your reply

**Comment by vinayakumarr** [comment]
make generates different error this time. Could you please look at this error
![error](https://cloud.githubusercontent.com/assets/18217467/18435465/04e8041a-7911-11e6-8aca-1a05c7007558.png)

**Comment by fliphil** [comment]
@vinayakumarr Are you still getting that error? The map.h file should be contained in the src subdirectory.

**Comment by vinayakumarr** [comment]
no. works successfully. Everything is working. Could you please tell how to capture data using joy package in an intranet or in single system.

**Comment by davidmcgrew** [comment]
Have you read the workbench document, which gives a quick overview and walkthrough?https://github.com/davidmcgrew/joy/blob/master/workbench.pdf
